### ISSUE TITLE
编译gradle出错

### ISSUE THREAD

**Issue by Gemini701** [tingsky9985/Weixin_Recorder#1]
你好，提示信息如下，请问需要更改gradle哪些信息？
Error:Cause: com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

Consult IDE log for more details (Help | Show Log)

**Comment by tingsky9985** [comment]
您好，

这是两年前的demo，可能是gradle版本比较老。
您可以尝试修改如下文件的gradle配置，修改为您目前使用的gradle版本即可。
可参考：
gradle-wrapper.properties: 
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip //修改

build.gradle：
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3' //修改

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

我这边测试成功，有问题欢迎沟通。

**Comment by Gemini701** [comment]
你好，问题已经解决。
非常感谢耐心详细的解答！
